# 应用名称
spring:
  application:
    name: vue
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=UTC
    username: zhaofutao
    password: 123456
  devtools:
    add-properties: true
server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

